--- select everything from the table
select * from supply_chain_updated

----What is the total revenue generated by each product type?
select `Product type`, SUM(`Revenue generated`) AS Total_Revenue
FROM supply_chain_updated
GROUP BY `Product type`
ORDER BY Total_Revenue DESC;

----What is the average price of products for each product type?
SELECT `Product type`, AVG(`Price`) AS Average_Price
FROM supply_chain_updated
GROUP BY `Product type`;

-----How many units of each product type have been sold?
SELECT `Product type`, SUM(`Number of products sold`) AS Total_Units_Sold
FROM supply_chain_updated
GROUP BY `Product type`
ORDER BY Total_Units_Sold DESC;

----What is the current stock level for each product type?
SELECT `Product type`, SUM(`Stock levels`) AS Total_Stock
FROM supply_chain_updated
GROUP BY `Product type`;

----What is the total shipping cost associated with each product type?
SELECT `Product type`, SUM(`Shipping costs`) AS Total_Shipping_Cost
FROM supply_chain_updated
GROUP BY `Product type`
ORDER BY Total_Shipping_Cost DESC;

----Which products have high lead time variability?
SELECT `Product type`, `SKU`, `Lead times`, `Lead Time Variability Status`
FROM supply_chain_updated
WHERE `Lead Time Variability Status` = 'High Variability';

-----Which products are currently flagged for stock shortage?
SELECT `Product type`, `SKU`, `Stock levels`, `Stock Shortage Flag`
FROM supply_chain_updated
WHERE `Stock Shortage Flag` = 'Yes';

-----Which products have high defect rates?
SELECT `Product type`, `SKU`, `Defect rates`, `High Defect Flag`
FROM supply_chain_updated
WHERE `High Defect Flag` = 'Yes';

-----What is the cost per unit for each product type?
SELECT `Supplier name`, AVG(`Lead time`) AS Avg_Lead_Time
FROM supply_chain_updated
GROUP BY `Supplier name`
ORDER BY Avg_Lead_Time DESC;

-----What are the average lead times for each supplier?
SELECT `Product type`, AVG(`Profit Margin`) AS Avg_Profit_Margin
FROM supply_chain_updated
GROUP BY `Product type`
ORDER BY Avg_Profit_Margin DESC;

----What are the total shipping costs for each shipping carrier?
SELECT `Shipping carriers`, SUM(`Shipping costs`) AS Total_Shipping_Cost
FROM supply_chain_updated
GROUP BY `Shipping carriers`
ORDER BY Total_Shipping_Cost DESC;

----What is the average profit margin for each product type?
SELECT `Product type`, AVG(`Profit Margin`) AS Avg_Profit_Margin
FROM supply_chain_updated
GROUP BY `Product type`
ORDER BY Avg_Profit_Margin DESC;

-----How do inspection results vary by product type?
SELECT `Product type`, COUNT(`Inspection results`) AS Total_Inspections, 
SUM(CASE WHEN `Inspection results` = 'Fail' THEN 1 ELSE 0 END) AS Failed_Inspections
FROM supply_chain_updated
GROUP BY `Product type`;





